# Generated by Django 3.2 on 2022-09-03 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=50, verbose_name='出版社')),
                ('publisher_eng', models.CharField(blank=True, max_length=50, null=True, verbose_name='出版社_eng')),
                ('contents', models.TextField(verbose_name='コンテンツ')),
                ('incorporated', models.DateField(verbose_name='設立日')),
                ('post_day', models.DateField(null=True, verbose_name='投稿日')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher_label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default=None, max_length=20, verbose_name='ラベル')),
                ('label_eng', models.CharField(default=None, max_length=20, verbose_name='ラベルeng')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.publisher', verbose_name='出版者')),
            ],
        ),
    ]
