# Generated by Django 3.2 on 2022-09-03 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_publisher_publisher_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publisher_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.publisher', verbose_name='出版社情報'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher_label_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.publisher_label', verbose_name='レーベル'),
        ),
    ]
